#include <furi.h>
#include <furi_hal.h>
#include <furi_hal_usb_cdc.h>
#include <gui/gui.h>

// Define log tag
#define TAG "LOGICAL-ANAL"

#define COUNT(x) ((size_t)(sizeof(x) / sizeof((x)[0])))

#define CBC_NUM 1
// If true, send data to serial evry loop, ~ 350000 per sec
// If false, send to serial only change,  ~ 1040000 per sec
#define REAL_TIME true


static const GpioPin* gpios[] = {
    &gpio_ext_pc0,
    &gpio_ext_pc1,
    &gpio_ext_pc3,
    &gpio_ext_pb2,
    &gpio_ext_pb3,
    &gpio_ext_pa4,
    &gpio_ext_pa6,
    &gpio_ext_pa7
};


const char *CHAR_TO_BIN[256] = {
	[0x00] = "I  O  O  O  I  O  O  I  O  O  O  I  OO  I",
	[0x01] = "I  O  O  O  I  O  O  I  O  O   I   I  O I   I",
	[0x02] = "I  O  O  O  I  O  O  I  O   I   O  I  O2  I",
	[0x03] = "I  O  O  O  I  O  O  I  O   I    I   I  O3  I",
	[0x04] = "I  O  O  O  I  O  O  I   I   O  O  I  O4  I",
	[0x05] = "I  O  O  O  I  O  O  I   I   O   I   I  O5  I",
	[0x06] = "I  O  O  O  I  O  O  I   I    I   O  I  O6  I",
	[0x07] = "I  O  O  O  I  O  O  I   I    I    I   I  O7  I",
	[0x08] = "I  O  O  O  I  O   I   I  O  O  O  I  O8  I",
	[0x09] = "I  O  O  O  I  O   I   I  O  O   I   I  O9  I",
	[0x0a] = "I  O  O  O  I  O   I   I  O   I   O  I  OA  I",
	[0x0b] = "I  O  O  O  I  O   I   I  O   I    I   I  OB  I",
	[0x0c] = "I  O  O  O  I  O   I   I   I   O  O  I  OC  I",
	[0x0d] = "I  O  O  O  I  O   I   I   I   O   I   I  OD  I",
	[0x0e] = "I  O  O  O  I  O   I   I   I    I   O  I  OE  I",
	[0x0f] = "I  O  O  O  I  O   I   I   I    I    I   I  OF  I",
	[0x10] = "I  O  O  O  I   I   O  I  O  O  O  I   I O  I",
	[0x11] = "I  O  O  O  I   I   O  I  O  O   I   I   I  I   I",
	[0x12] = "I  O  O  O  I   I   O  I  O   I   O  I   I 2  I",
	[0x13] = "I  O  O  O  I   I   O  I  O   I    I   I   I 3  I",
	[0x14] = "I  O  O  O  I   I   O  I   I   O  O  I   I 4  I",
	[0x15] = "I  O  O  O  I   I   O  I   I   O   I   I   I 5  I",
	[0x16] = "I  O  O  O  I   I   O  I   I    I   O  I   I 6  I",
	[0x17] = "I  O  O  O  I   I   O  I   I    I    I   I   I 7  I",
	[0x18] = "I  O  O  O  I   I    I   I  O  O  O  I   I 8  I",
	[0x19] = "I  O  O  O  I   I    I   I  O  O   I   I   I 9  I",
	[0x1a] = "I  O  O  O  I   I    I   I  O   I   O  I   I A  I",
	[0x1b] = "I  O  O  O  I   I    I   I  O   I    I   I   I B  I",
	[0x1c] = "I  O  O  O  I   I    I   I   I   O  O  I   I C  I",
	[0x1d] = "I  O  O  O  I   I    I   I   I   O   I   I   I D  I",
	[0x1e] = "I  O  O  O  I   I    I   I   I    I   O  I   I E  I",
	[0x1f] = "I  O  O  O  I   I    I   I   I    I    I   I   I F  I",
	[0x20] = "I  O  O   I   I  O  O  I  O  O  O  I  2O  I",
	[0x21] = "I  O  O   I   I  O  O  I  O  O   I   I  2 I   I",
	[0x22] = "I  O  O   I   I  O  O  I  O   I   O  I  22  I",
	[0x23] = "I  O  O   I   I  O  O  I  O   I    I   I  23  I",
	[0x24] = "I  O  O   I   I  O  O  I   I   O  O  I  24  I",
	[0x25] = "I  O  O   I   I  O  O  I   I   O   I   I  25  I",
	[0x26] = "I  O  O   I   I  O  O  I   I    I   O  I  26  I",
	[0x27] = "I  O  O   I   I  O  O  I   I    I    I   I  27  I",
	[0x28] = "I  O  O   I   I  O   I   I  O  O  O  I  28  I",
	[0x29] = "I  O  O   I   I  O   I   I  O  O   I   I  29  I",
	[0x2a] = "I  O  O   I   I  O   I   I  O   I   O  I  2A  I",
	[0x2b] = "I  O  O   I   I  O   I   I  O   I    I   I  2B  I",
	[0x2c] = "I  O  O   I   I  O   I   I   I   O  O  I  2C  I",
	[0x2d] = "I  O  O   I   I  O   I   I   I   O   I   I  2D  I",
	[0x2e] = "I  O  O   I   I  O   I   I   I    I   O  I  2E  I",
	[0x2f] = "I  O  O   I   I  O   I   I   I    I    I   I  2F  I",
	[0x30] = "I  O  O   I   I   I   O  I  O  O  O  I  3O  I",
	[0x31] = "I  O  O   I   I   I   O  I  O  O   I   I  3 I   I",
	[0x32] = "I  O  O   I   I   I   O  I  O   I   O  I  32  I",
	[0x33] = "I  O  O   I   I   I   O  I  O   I    I   I  33  I",
	[0x34] = "I  O  O   I   I   I   O  I   I   O  O  I  34  I",
	[0x35] = "I  O  O   I   I   I   O  I   I   O   I   I  35  I",
	[0x36] = "I  O  O   I   I   I   O  I   I    I   O  I  36  I",
	[0x37] = "I  O  O   I   I   I   O  I   I    I    I   I  37  I",
	[0x38] = "I  O  O   I   I   I    I   I  O  O  O  I  38  I",
	[0x39] = "I  O  O   I   I   I    I   I  O  O   I   I  39  I",
	[0x3a] = "I  O  O   I   I   I    I   I  O   I   O  I  3A  I",
	[0x3b] = "I  O  O   I   I   I    I   I  O   I    I   I  3B  I",
	[0x3c] = "I  O  O   I   I   I    I   I   I   O  O  I  3C  I",
	[0x3d] = "I  O  O   I   I   I    I   I   I   O   I   I  3D  I",
	[0x3e] = "I  O  O   I   I   I    I   I   I    I   O  I  3E  I",
	[0x3f] = "I  O  O   I   I   I    I   I   I    I    I   I  3F  I",
	[0x40] = "I  O   I   O  I  O  O  I  O  O  O  I  4O  I",
	[0x41] = "I  O   I   O  I  O  O  I  O  O   I   I  4 I   I",
	[0x42] = "I  O   I   O  I  O  O  I  O   I   O  I  42  I",
	[0x43] = "I  O   I   O  I  O  O  I  O   I    I   I  43  I",
	[0x44] = "I  O   I   O  I  O  O  I   I   O  O  I  44  I",
	[0x45] = "I  O   I   O  I  O  O  I   I   O   I   I  45  I",
	[0x46] = "I  O   I   O  I  O  O  I   I    I   O  I  46  I",
	[0x47] = "I  O   I   O  I  O  O  I   I    I    I   I  47  I",
	[0x48] = "I  O   I   O  I  O   I   I  O  O  O  I  48  I",
	[0x49] = "I  O   I   O  I  O   I   I  O  O   I   I  49  I",
	[0x4a] = "I  O   I   O  I  O   I   I  O   I   O  I  4A  I",
	[0x4b] = "I  O   I   O  I  O   I   I  O   I    I   I  4B  I",
	[0x4c] = "I  O   I   O  I  O   I   I   I   O  O  I  4C  I",
	[0x4d] = "I  O   I   O  I  O   I   I   I   O   I   I  4D  I",
	[0x4e] = "I  O   I   O  I  O   I   I   I    I   O  I  4E  I",
	[0x4f] = "I  O   I   O  I  O   I   I   I    I    I   I  4F  I",
	[0x50] = "I  O   I   O  I   I   O  I  O  O  O  I  5O  I",
	[0x51] = "I  O   I   O  I   I   O  I  O  O   I   I  5 I   I",
	[0x52] = "I  O   I   O  I   I   O  I  O   I   O  I  52  I",
	[0x53] = "I  O   I   O  I   I   O  I  O   I    I   I  53  I",
	[0x54] = "I  O   I   O  I   I   O  I   I   O  O  I  54  I",
	[0x55] = "I  O   I   O  I   I   O  I   I   O   I   I  55  I",
	[0x56] = "I  O   I   O  I   I   O  I   I    I   O  I  56  I",
	[0x57] = "I  O   I   O  I   I   O  I   I    I    I   I  57  I",
	[0x58] = "I  O   I   O  I   I    I   I  O  O  O  I  58  I",
	[0x59] = "I  O   I   O  I   I    I   I  O  O   I   I  59  I",
	[0x5a] = "I  O   I   O  I   I    I   I  O   I   O  I  5A  I",
	[0x5b] = "I  O   I   O  I   I    I   I  O   I    I   I  5B  I",
	[0x5c] = "I  O   I   O  I   I    I   I   I   O  O  I  5C  I",
	[0x5d] = "I  O   I   O  I   I    I   I   I   O   I   I  5D  I",
	[0x5e] = "I  O   I   O  I   I    I   I   I    I   O  I  5E  I",
	[0x5f] = "I  O   I   O  I   I    I   I   I    I    I   I  5F  I",
	[0x60] = "I  O   I    I   I  O  O  I  O  O  O  I  6O  I",
	[0x61] = "I  O   I    I   I  O  O  I  O  O   I   I  6 I   I",
	[0x62] = "I  O   I    I   I  O  O  I  O   I   O  I  62  I",
	[0x63] = "I  O   I    I   I  O  O  I  O   I    I   I  63  I",
	[0x64] = "I  O   I    I   I  O  O  I   I   O  O  I  64  I",
	[0x65] = "I  O   I    I   I  O  O  I   I   O   I   I  65  I",
	[0x66] = "I  O   I    I   I  O  O  I   I    I   O  I  66  I",
	[0x67] = "I  O   I    I   I  O  O  I   I    I    I   I  67  I",
	[0x68] = "I  O   I    I   I  O   I   I  O  O  O  I  68  I",
	[0x69] = "I  O   I    I   I  O   I   I  O  O   I   I  69  I",
	[0x6a] = "I  O   I    I   I  O   I   I  O   I   O  I  6A  I",
	[0x6b] = "I  O   I    I   I  O   I   I  O   I    I   I  6B  I",
	[0x6c] = "I  O   I    I   I  O   I   I   I   O  O  I  6C  I",
	[0x6d] = "I  O   I    I   I  O   I   I   I   O   I   I  6D  I",
	[0x6e] = "I  O   I    I   I  O   I   I   I    I   O  I  6E  I",
	[0x6f] = "I  O   I    I   I  O   I   I   I    I    I   I  6F  I",
	[0x70] = "I  O   I    I   I   I   O  I  O  O  O  I  7O  I",
	[0x71] = "I  O   I    I   I   I   O  I  O  O   I   I  7 I   I",
	[0x72] = "I  O   I    I   I   I   O  I  O   I   O  I  72  I",
	[0x73] = "I  O   I    I   I   I   O  I  O   I    I   I  73  I",
	[0x74] = "I  O   I    I   I   I   O  I   I   O  O  I  74  I",
	[0x75] = "I  O   I    I   I   I   O  I   I   O   I   I  75  I",
	[0x76] = "I  O   I    I   I   I   O  I   I    I   O  I  76  I",
	[0x77] = "I  O   I    I   I   I   O  I   I    I    I   I  77  I",
	[0x78] = "I  O   I    I   I   I    I   I  O  O  O  I  78  I",
	[0x79] = "I  O   I    I   I   I    I   I  O  O   I   I  79  I",
	[0x7a] = "I  O   I    I   I   I    I   I  O   I   O  I  7A  I",
	[0x7b] = "I  O   I    I   I   I    I   I  O   I    I   I  7B  I",
	[0x7c] = "I  O   I    I   I   I    I   I   I   O  O  I  7C  I",
	[0x7d] = "I  O   I    I   I   I    I   I   I   O   I   I  7D  I",
	[0x7e] = "I  O   I    I   I   I    I   I   I    I   O  I  7E  I",
	[0x7f] = "I  O   I    I   I   I    I   I   I    I    I   I  7F  I",
	[0x80] = "I   I   O  O  I  O  O  I  O  O  O  I  8O  I",
	[0x81] = "I   I   O  O  I  O  O  I  O  O   I   I  8 I   I",
	[0x82] = "I   I   O  O  I  O  O  I  O   I   O  I  82  I",
	[0x83] = "I   I   O  O  I  O  O  I  O   I    I   I  83  I",
	[0x84] = "I   I   O  O  I  O  O  I   I   O  O  I  84  I",
	[0x85] = "I   I   O  O  I  O  O  I   I   O   I   I  85  I",
	[0x86] = "I   I   O  O  I  O  O  I   I    I   O  I  86  I",
	[0x87] = "I   I   O  O  I  O  O  I   I    I    I   I  87  I",
	[0x88] = "I   I   O  O  I  O   I   I  O  O  O  I  88  I",
	[0x89] = "I   I   O  O  I  O   I   I  O  O   I   I  89  I",
	[0x8a] = "I   I   O  O  I  O   I   I  O   I   O  I  8A  I",
	[0x8b] = "I   I   O  O  I  O   I   I  O   I    I   I  8B  I",
	[0x8c] = "I   I   O  O  I  O   I   I   I   O  O  I  8C  I",
	[0x8d] = "I   I   O  O  I  O   I   I   I   O   I   I  8D  I",
	[0x8e] = "I   I   O  O  I  O   I   I   I    I   O  I  8E  I",
	[0x8f] = "I   I   O  O  I  O   I   I   I    I    I   I  8F  I",
	[0x90] = "I   I   O  O  I   I   O  I  O  O  O  I  9O  I",
	[0x91] = "I   I   O  O  I   I   O  I  O  O   I   I  9 I   I",
	[0x92] = "I   I   O  O  I   I   O  I  O   I   O  I  92  I",
	[0x93] = "I   I   O  O  I   I   O  I  O   I    I   I  93  I",
	[0x94] = "I   I   O  O  I   I   O  I   I   O  O  I  94  I",
	[0x95] = "I   I   O  O  I   I   O  I   I   O   I   I  95  I",
	[0x96] = "I   I   O  O  I   I   O  I   I    I   O  I  96  I",
	[0x97] = "I   I   O  O  I   I   O  I   I    I    I   I  97  I",
	[0x98] = "I   I   O  O  I   I    I   I  O  O  O  I  98  I",
	[0x99] = "I   I   O  O  I   I    I   I  O  O   I   I  99  I",
	[0x9a] = "I   I   O  O  I   I    I   I  O   I   O  I  9A  I",
	[0x9b] = "I   I   O  O  I   I    I   I  O   I    I   I  9B  I",
	[0x9c] = "I   I   O  O  I   I    I   I   I   O  O  I  9C  I",
	[0x9d] = "I   I   O  O  I   I    I   I   I   O   I   I  9D  I",
	[0x9e] = "I   I   O  O  I   I    I   I   I    I   O  I  9E  I",
	[0x9f] = "I   I   O  O  I   I    I   I   I    I    I   I  9F  I",
	[0xa0] = "I   I   O   I   I  O  O  I  O  O  O  I  AO  I",
	[0xa1] = "I   I   O   I   I  O  O  I  O  O   I   I  A I   I",
	[0xa2] = "I   I   O   I   I  O  O  I  O   I   O  I  A2  I",
	[0xa3] = "I   I   O   I   I  O  O  I  O   I    I   I  A3  I",
	[0xa4] = "I   I   O   I   I  O  O  I   I   O  O  I  A4  I",
	[0xa5] = "I   I   O   I   I  O  O  I   I   O   I   I  A5  I",
	[0xa6] = "I   I   O   I   I  O  O  I   I    I   O  I  A6  I",
	[0xa7] = "I   I   O   I   I  O  O  I   I    I    I   I  A7  I",
	[0xa8] = "I   I   O   I   I  O   I   I  O  O  O  I  A8  I",
	[0xa9] = "I   I   O   I   I  O   I   I  O  O   I   I  A9  I",
	[0xaa] = "I   I   O   I   I  O   I   I  O   I   O  I  AA  I",
	[0xab] = "I   I   O   I   I  O   I   I  O   I    I   I  AB  I",
	[0xac] = "I   I   O   I   I  O   I   I   I   O  O  I  AC  I",
	[0xad] = "I   I   O   I   I  O   I   I   I   O   I   I  AD  I",
	[0xae] = "I   I   O   I   I  O   I   I   I    I   O  I  AE  I",
	[0xaf] = "I   I   O   I   I  O   I   I   I    I    I   I  AF  I",
	[0xb0] = "I   I   O   I   I   I   O  I  O  O  O  I  BO  I",
	[0xb1] = "I   I   O   I   I   I   O  I  O  O   I   I  B I   I",
	[0xb2] = "I   I   O   I   I   I   O  I  O   I   O  I  B2  I",
	[0xb3] = "I   I   O   I   I   I   O  I  O   I    I   I  B3  I",
	[0xb4] = "I   I   O   I   I   I   O  I   I   O  O  I  B4  I",
	[0xb5] = "I   I   O   I   I   I   O  I   I   O   I   I  B5  I",
	[0xb6] = "I   I   O   I   I   I   O  I   I    I   O  I  B6  I",
	[0xb7] = "I   I   O   I   I   I   O  I   I    I    I   I  B7  I",
	[0xb8] = "I   I   O   I   I   I    I   I  O  O  O  I  B8  I",
	[0xb9] = "I   I   O   I   I   I    I   I  O  O   I   I  B9  I",
	[0xba] = "I   I   O   I   I   I    I   I  O   I   O  I  BA  I",
	[0xbb] = "I   I   O   I   I   I    I   I  O   I    I   I  BB  I",
	[0xbc] = "I   I   O   I   I   I    I   I   I   O  O  I  BC  I",
	[0xbd] = "I   I   O   I   I   I    I   I   I   O   I   I  BD  I",
	[0xbe] = "I   I   O   I   I   I    I   I   I    I   O  I  BE  I",
	[0xbf] = "I   I   O   I   I   I    I   I   I    I    I   I  BF  I",
	[0xc0] = "I   I    I   O  I  O  O  I  O  O  O  I  CO  I",
	[0xc1] = "I   I    I   O  I  O  O  I  O  O   I   I  C I   I",
	[0xc2] = "I   I    I   O  I  O  O  I  O   I   O  I  C2  I",
	[0xc3] = "I   I    I   O  I  O  O  I  O   I    I   I  C3  I",
	[0xc4] = "I   I    I   O  I  O  O  I   I   O  O  I  C4  I",
	[0xc5] = "I   I    I   O  I  O  O  I   I   O   I   I  C5  I",
	[0xc6] = "I   I    I   O  I  O  O  I   I    I   O  I  C6  I",
	[0xc7] = "I   I    I   O  I  O  O  I   I    I    I   I  C7  I",
	[0xc8] = "I   I    I   O  I  O   I   I  O  O  O  I  C8  I",
	[0xc9] = "I   I    I   O  I  O   I   I  O  O   I   I  C9  I",
	[0xca] = "I   I    I   O  I  O   I   I  O   I   O  I  CA  I",
	[0xcb] = "I   I    I   O  I  O   I   I  O   I    I   I  CB  I",
	[0xcc] = "I   I    I   O  I  O   I   I   I   O  O  I  CC  I",
	[0xcd] = "I   I    I   O  I  O   I   I   I   O   I   I  CD  I",
	[0xce] = "I   I    I   O  I  O   I   I   I    I   O  I  CE  I",
	[0xcf] = "I   I    I   O  I  O   I   I   I    I    I   I  CF  I",
	[0xd0] = "I   I    I   O  I   I   O  I  O  O  O  I  DO  I",
	[0xd1] = "I   I    I   O  I   I   O  I  O  O   I   I  D I   I",
	[0xd2] = "I   I    I   O  I   I   O  I  O   I   O  I  D2  I",
	[0xd3] = "I   I    I   O  I   I   O  I  O   I    I   I  D3  I",
	[0xd4] = "I   I    I   O  I   I   O  I   I   O  O  I  D4  I",
	[0xd5] = "I   I    I   O  I   I   O  I   I   O   I   I  D5  I",
	[0xd6] = "I   I    I   O  I   I   O  I   I    I   O  I  D6  I",
	[0xd7] = "I   I    I   O  I   I   O  I   I    I    I   I  D7  I",
	[0xd8] = "I   I    I   O  I   I    I   I  O  O  O  I  D8  I",
	[0xd9] = "I   I    I   O  I   I    I   I  O  O   I   I  D9  I",
	[0xda] = "I   I    I   O  I   I    I   I  O   I   O  I  DA  I",
	[0xdb] = "I   I    I   O  I   I    I   I  O   I    I   I  DB  I",
	[0xdc] = "I   I    I   O  I   I    I   I   I   O  O  I  DC  I",
	[0xdd] = "I   I    I   O  I   I    I   I   I   O   I   I  DD  I",
	[0xde] = "I   I    I   O  I   I    I   I   I    I   O  I  DE  I",
	[0xdf] = "I   I    I   O  I   I    I   I   I    I    I   I  DF  I",
	[0xe0] = "I   I    I    I   I  O  O  I  O  O  O  I  EO  I",
	[0xe1] = "I   I    I    I   I  O  O  I  O  O   I   I  E I   I",
	[0xe2] = "I   I    I    I   I  O  O  I  O   I   O  I  E2  I",
	[0xe3] = "I   I    I    I   I  O  O  I  O   I    I   I  E3  I",
	[0xe4] = "I   I    I    I   I  O  O  I   I   O  O  I  E4  I",
	[0xe5] = "I   I    I    I   I  O  O  I   I   O   I   I  E5  I",
	[0xe6] = "I   I    I    I   I  O  O  I   I    I   O  I  E6  I",
	[0xe7] = "I   I    I    I   I  O  O  I   I    I    I   I  E7  I",
	[0xe8] = "I   I    I    I   I  O   I   I  O  O  O  I  E8  I",
	[0xe9] = "I   I    I    I   I  O   I   I  O  O   I   I  E9  I",
	[0xea] = "I   I    I    I   I  O   I   I  O   I   O  I  EA  I",
	[0xeb] = "I   I    I    I   I  O   I   I  O   I    I   I  EB  I",
	[0xec] = "I   I    I    I   I  O   I   I   I   O  O  I  EC  I",
	[0xed] = "I   I    I    I   I  O   I   I   I   O   I   I  ED  I",
	[0xee] = "I   I    I    I   I  O   I   I   I    I   O  I  EE  I",
	[0xef] = "I   I    I    I   I  O   I   I   I    I    I   I  EF  I",
	[0xf0] = "I   I    I    I   I   I   O  I  O  O  O  I  FO  I",
	[0xf1] = "I   I    I    I   I   I   O  I  O  O   I   I  F I   I",
	[0xf2] = "I   I    I    I   I   I   O  I  O   I   O  I  F2  I",
	[0xf3] = "I   I    I    I   I   I   O  I  O   I    I   I  F3  I",
	[0xf4] = "I   I    I    I   I   I   O  I   I   O  O  I  F4  I",
	[0xf5] = "I   I    I    I   I   I   O  I   I   O   I   I  F5  I",
	[0xf6] = "I   I    I    I   I   I   O  I   I    I   O  I  F6  I",
	[0xf7] = "I   I    I    I   I   I   O  I   I    I    I   I  F7  I",
	[0xf8] = "I   I    I    I   I   I    I   I  O  O  O  I  F8  I",
	[0xf9] = "I   I    I    I   I   I    I   I  O  O   I   I  F9  I",
	[0xfa] = "I   I    I    I   I   I    I   I  O   I   O  I  FA  I",
	[0xfb] = "I   I    I    I   I   I    I   I  O   I    I   I  FB  I",
	[0xfc] = "I   I    I    I   I   I    I   I   I   O  O  I  FC  I",
	[0xfd] = "I   I    I    I   I   I    I   I   I   O   I   I  FD  I",
	[0xfe] = "I   I    I    I   I   I    I   I   I    I   O  I  FE  I",
	[0xff] = "I   I    I    I   I   I    I   I   I    I    I   I  FF  I",
};


typedef struct {
    Gui* gui;
    Canvas* canvas;

    FuriPubSub* input;
    FuriPubSubSubscription* input_subscription;
    
    bool is_runing;
	unsigned int test;
} App;
